### PR TITLE
ci: add pipeline for storage network

### PR DESCRIPTION
**Pull request by yangchiu**
ci: add pipeline for storage network

For https://github.com/longhorn/longhorn/issues/4218

Signed-off-by: Yang Chiu [yang.chiu@suse.com](mailto:yang.chiu@suse.com)

### CODE REVIEW

**Review by c3y1huang — APPROVED** [review]
Adding options to configure the Multus version and perhaps the plugin type (thin/thick) would be a nice enhancement.

**Comment by innobead** [comment]
> LGTM! Adding options to configure the Multus version and perhaps the plugin type (thin/thick) would be a nice enhancement.

@yangchiu can we improve this part?

**Comment by yangchiu** [comment]
> LGTM! Adding options to configure the Multus version 

ok.

> and perhaps the plugin type (thin/thick) would be a nice enhancement.

Thick plugin's never been tested before. Manual testing will be done first before implement it into pipeline.

**Comment by c3y1huang** [comment]
> Thick plugin's never been tested before. Manual testing will be done first before implement it into pipeline.

https://github.com/longhorn/longhorn-tests/pull/1584

**Comment by yangchiu** [comment]
> LGTM! Adding options to configure the Multus version and perhaps the plugin type (thin/thick) would be a nice enhancement.

Parameters `MULTUS_VERSION` and `THICK_PLUGIN` added.

**Review by innobead — APPROVED** [review]

**Pull request merged**
