### PR TITLE
update master pipeline upgrade test version

### PR DESCRIPTION
**Pull request by chriscchien**
Update upgrade test version in master pipeline for v1.5.0 released

(1) upgrade test: LONGHORN_STABLE_VERSION=v1.5.0
(2) 2 stage upgrade test: LONGHORN_STABLE_VERSION=v1.4.3, LONGHORN_TRANSIENT_VERSION=v1.5.0

### CODE REVIEW

**Review by yangchiu — DISMISSED** [review]
LGTM

**Comment by innobead** [comment]
> @innobead Since `v1.5.0` is a problematic release, should we test this upgrade path? Or we should use `v1.5.1` instead?
> 
> Like:
> 
> ```
> v1.5.1 -> master-head
> v1.4.3 -> v1.5.1 -> master-head
> ```

Sounds good.

**Comment by yangchiu** [comment]
> > @innobead Since `v1.5.0` is a problematic release, should we test this upgrade path? Or we should use `v1.5.1` instead?
> > Like:
> > ```
> > v1.5.1 -> master-head
> > v1.4.3 -> v1.5.1 -> master-head
> > ```
> 
> Sounds good.

cc @chriscchien Could you help to refine this?

**Comment by chriscchien** [comment]
Updated!

**Review by yangchiu — APPROVED** [review]
LGTM

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@yangchiu go ahead to merge.

**Pull request merged**
