### PR TITLE
Update regression job k8s version to v1.29 and LONGHORN_STABLE_VERSIO to v1.6.1.

### PR DESCRIPTION
**Pull request by roger-ryao**
1. Update `v1.6.x`/`master` LONGHORN_STABLE_VERSION to `v1.6.1`
2. Update regression job k8s version to `v1.29`

ref. https://github.com/longhorn/longhorn/issues/8239

Signed-off-by: Roger Yao <roger.yao@suse.com>

### CODE REVIEW

**Comment by yangchiu** [comment]
@roger-ryao Has a full regression been run on this k8s version? And could you add reviewers of this PR?

**Comment by roger-ryao** [comment]
> nd could you add reviewers of this PR

Hi @yangchiu 
    1. For `v1.29.3`, I have only run this regression once: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6723/
     2. I do not have permission to add reviewers to this PR.

**Comment by yangchiu** [comment]
> 1. For v1.29.3, I have only run this regression once

@roger-ryao Thank you! But how about `rke2`?

> 2. I do not have permission to add reviewers to this PR.

@innobead Is it possible to make @roger-ryao have the right permission? Thank you!

**Comment by roger-ryao** [comment]
> > 1. For v1.29.3, I have only run this regression once
> 
> @roger-ryao Thank you! But how about `rke2`?

Hi @yangchiu 
The test result for `v1.29.2+rke2r1` is without any outstanding issues.
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6755/

Screenshot_20240424_145237

**Review by yangchiu — APPROVED** [review]
LGTM

**Pull request merged**
