### PR TITLE
ci: Bump OS distro version for Longhorn v1.8.0

### PR DESCRIPTION
**Pull request by roger-ryao**
https://github.com/longhorn/longhorn/issues/9879

* Rockylinux, `9.5`
  - [x] amd64: https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/amd64/job/longhorn-tests-rockylinux-amd64/44/
  - [x] arm64: https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/arm64/job/longhorn-tests-rockylinux-arm64/69/
* RHEL `9.5.0`
  - [x] amd64: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/182/ 
  - [x] arm64: https://ci.longhorn.io/job/public/job/master/job/rhel/job/arm64/job/longhorn-tests-rhel-arm64/100/
* Oracle `9.4`
  - [x] amd64: https://ci.longhorn.io/job/public/job/master/job/oracle/job/amd64/job/longhorn-tests-oracle-amd64/38

### CODE REVIEW

**Review by yangchiu — CHANGES_REQUESTED** [review]
Could you clarify why we need to switch to using the t4g.xlarge machine type?

**Comment by yangchiu** [comment]
Could we clarify why the following test cases failed first?

https://ci.longhorn.io/job/public/job/master/job/oracle/job/amd64/job/longhorn-tests-oracle-amd64/38/testReport/
https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/arm64/job/longhorn-tests-rockylinux-arm64/69/testReport/

**Comment by roger-ryao** [comment]
> Could you clarify why we need to switch to using the t4g.xlarge machine type?

During my testing, I found that when adding an EC2 instance of type `a1.2xlarge` using the `RHEL` and `Rocky Linux` `ARM64` images, the instance status checks remain at `Initializing`, and I cannot SSH into it. I did not find any error clues. I manually added an instance and noticed that the recommended instance type was `t4g.xxx`, which worked correctly when I tested it with `t4g.xlarge` using `ARM64`. However, the drawback of this type is that the network performance is limited to only `5 Gigabytes`.

Screenshot_20241204_121527

**Comment by roger-ryao** [comment]
> Could we clarify why the following test cases failed first?
> 
> https://ci.longhorn.io/job/public/job/master/job/oracle/job/amd64/job/longhorn-tests-oracle-amd64/38/testReport/ 
> https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/arm64/job/longhorn-tests-rockylinux-arm64/69/testReport/

The two failed test reruns almost passed, except for the test case [test_metric_longhorn_volume_file_system_read_only](https://ci.longhorn.io/job/public/job/master/job/oracle/job/amd64/job/longhorn-tests-oracle-amd64/38/testReport/junit/tests/test_metric/test_metric_longhorn_volume_file_system_read_only/), which still `FAILED`. We have a ticket to track this issue: [Longhorn Issue #9553](https://github.com/longhorn/longhorn/issues/9553).

`Oracle linux` `AMD64`: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7733/testReport/
`Rocky Linux` `ARM64`: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7732/testReport/

**Review by yangchiu — APPROVED** [review]

**Pull request merged**
